In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
from itertools import combinations
from random import random
import numpy as np

In [116]:
x = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[-1, -2, -3],
               [-4, -5, -6],
               [-7, -8, -9]],
               [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])
x.shape

(3, 3, 3)

In [117]:
y = x.ravel() # flatten out to a 1D array
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -1, -2, -3, -4, -5, -6, -7, -8,
       -9,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [118]:
print(x[1,2,0])
lin_index = np.where(y == x[1,2,0])
lin_index[0][0]

-7


15

In [119]:
def find_lin_ind(i, j, k, n):
    return (i * n ** 2 + j * n + k)

In [120]:
#
# Generate n-dimensional tensor
#
# # n = 3
# row = np.array([0 for i in range(0, n)])
# # row
# x = np.array([np.array([row for i in range(n)]) for i in range(n)])
# x


In [121]:
def add_all(i, j, k, g):
    g[i, j, k] = 1 
    g[i, k, j] = 1      
    g[j, i, k] = 1
    g[j, k, i] = 1
    g[k, i, j] = 1
    g[k, j, i] = 1
    return(g)

In [122]:
# g: tensor
# n: rank of the tensor
# p: probability of creating edges
def generate_graph(n, p):  
    g = np.array([np.array([np.array([0 for i in range(0, n)]) for i in range(n)]) for i in range(n)])
    vec = np.array([0 for i in range(0, n)])
    print(vec)
    # Set edges
    for i in range(n):
        for j in range(i+1, n):
            for k in range(j+1, n):
                a = np.random.rand()
                # print(a)
                if a < p:
                    vec[i] += 1
                    vec[j] += 1
                    vec[k] += 1
                    add_all(i, j, k, g)
    return g, vec


In [123]:
n = 4
p = 0.5
res = generate_graph(n, p)

[0 0 0 0]


In [124]:
res[0]

array([[[0, 0, 0, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [0, 1, 0, 0]],

       [[0, 0, 1, 1],
        [0, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 0, 1, 0]],

       [[0, 1, 0, 0],
        [1, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 1, 0, 0]],

       [[0, 1, 0, 0],
        [1, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 0]]])

In [125]:
V = res[1]
V

array([2, 3, 2, 2])

In [126]:
np.flip(np.argsort(V)) # sort the indices


array([1, 3, 2, 0])

In [127]:
def remove_all(i, j, k, g):
    g[i, j, k] = 0 
    g[i, k, j] = 0      
    g[j, i, k] = 0
    g[j, k, i] = 0
    g[k, i, j] = 0
    g[k, j, i] = 0
    return(g)


In [128]:
# remove edge
def remove_edges(g, n, vec, curr):
    vec[curr] = 0
    A = g.copy()
    for j in range(0, n):
        for k in range(0, n):
            if A[curr, j, k] == 1:
                vec[j] -= 1
                vec[k] -= 1
                remove_all(curr, j, k, A)
    return(A)


In [136]:
remove_edges(G, n, V, V[0])

array([[[0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 1, 0, 0]],

       [[0, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [1, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [130]:
G = res[0]
G

array([[[0, 0, 0, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [0, 1, 0, 0]],

       [[0, 0, 1, 1],
        [0, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 0, 1, 0]],

       [[0, 1, 0, 0],
        [1, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 1, 0, 0]],

       [[0, 1, 0, 0],
        [1, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
active_count
edge_sum

In [ ]:
def is_clique(g, n):
    active_count = 0
    edge_sum = 0
     for i in range(n):
        for j in range(i+1, n):
            for k in range(j+1, n):
                if g[i, j, k]