In [55]:
%matplotlib inline
import matplotlib.pyplot as plt
from itertools import combinations
from random import random
import numpy as np

In [56]:
x = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[-1, -2, -3],
               [-4, -5, -6],
               [-7, -8, -9]],
               [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])
x.shape

(3, 3, 3)

In [57]:
y = x.ravel() # flatten out to a 1D array
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -1, -2, -3, -4, -5, -6, -7, -8,
       -9,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [58]:
print(x[1,2,0])
lin_index = np.where(y == x[1,2,0])
lin_index[0][0]

-7


15

In [59]:
def find_lin_ind(i, j, k, n):
    return (i * n ** 2 + j * n + k)

In [60]:
#
# Generate n-dimensional tensor
#
# # n = 3
# row = np.array([0 for i in range(0, n)])
# # row
# x = np.array([np.array([row for i in range(n)]) for i in range(n)])
# x


In [61]:
# g: tensor
# n: rank of the tensor
# p: probability of creating edges
def generate_graph(n, p):
    # Generate n-dimensional tensor
    # row = np.array([0 for i in range(0, n)])
    g = np.array([np.array([np.array([0 for i in range(0, n)]) for i in range(n)]) for i in range(n)])

    # generate 1-by-n^3 vector to track every node; 1 if included in a graph
    vec = g.ravel()
    print(vec)

    # Set edges
    for i in range(n):
        for j in range(n):
            for k in range(n):
                a = np.random.rand()
                # print(a)
                if a < p:
                    g[i, j, k] = 1
                    print(g)
                    vec[find_lin_ind(i, j, k, n)] += 1
                    print(vec)
                    g[i, k, j] = 1
                    vec[find_lin_ind(i, k, j, n)] += 1
                    g[j, i, k] = 1
                    vec[find_lin_ind(j, i, k,n)] += 1
                    g[j, k, i] = 1
                    vec[find_lin_ind(j, k, i, n)] += 1
                    g[k, i, j] = 1
                    vec[find_lin_ind(k, i, j, n)] += 1
                    g[k, j, i] = 1
                    vec[find_lin_ind(k, j, i, n)] += 1
    return g, vec

In [68]:
n = 3
p = 0.5
res = generate_graph(3, 0.5)
G = res[0]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[[0 0 1]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[[0 0 2]
  [1 0 0]
  [2 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[2 0 0]
  [0 0 0]
  [0 0 0]]]
[0 0 2 2 0 0 2 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
[[[0 2 2]
  [2 0 1]
  [2 0 0]]

 [[2 0 0]
  [0 0 0]
  [0 0 0]]

 [[2 0 0]
  [0 0 0]
  [0 0 0]]]
[0 2 2 2 0 2 2 0 0 2 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
[[[0 2 2]
  [2 0 2]
  [1 2 0]]

 [[2 0 2]
  [0 0 0]
  [2 0 0]]

 [[2 2 0]
  [2 0 0]
  [0 0 0]]]
[0 2 2 2 0 2 2 2 0 2 0 2 0 0 0 2 0 0 2 2 0 2 0 0 0 0 0]
[[[0 2 2]
  [2 0 2]
  [2 1 0]]

 [[2 0 2]
  [0 0 0]
  [2 0 0]]

 [[2 2 0]
  [2 0 0]
  [0 0 0]]]
[0 2 2 2 0 2 2 2 0 2 0 2 0 0 0 2 0 0 2 2 0 2 0 0 0 0 0]
[[[0 2 2]
  [2 0 2]
  [2 2 1]]

 [[2 0 2]
  [0 0 0]
  [2 0 0]]

 [[2 2 0]
  [2 0 0]
  [0 0 0]]]
[0 2 2 2 0 2 2 2 2 2 0 2 0 0 0 2 0 0 2 2 0 2 0 0 0 0 0]
[[[0 2 2]
  [2 0 2]
  [2 2 2]]



In [63]:
# vec = res[1]
# vec


In [ ]:
# generate #s random subets of the original graph of size n
def generate_subgraph(g, s, n):
    for i in range(s):
        for 
            g[i, j, k] == 1

In [ ]:
import random
# n: size
# order: k
def generate_random_hypergraph(order, n):
    nodes = set(range(order))
    edges = set()
    while len(edges) < size:
        edge_size = random.randint(2, order)
        edge = frozenset(random.sample(nodes, k=edge_size))
        if edge not in edges:
          edges.add(edge)
    return {'nodes': nodes, 'edges': edges}

In [69]:
MAX = 5;

# list of the vertices - 1D array
vertices = [0]* MAX;
print(vertices)

# Graph - 
graph = np.zeros((MAX, MAX));
print(graph)

# Degree of the vertices
d = [0] * MAX;

[0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [70]:
# Function to print the clique
def print_clique(n) :

	for i in range(1, n) :
		print(vertices[i], end = " ");
	print(",", end=" ");

In [71]:
# recursively  find all the cliques of size s
def find_clique(i, l, k) :

	# Check if any vertices from i+1 can be inserted
	for j in range( i + 1, n -(k - l) + 1) :

		# If the degree of the graph is sufficient
		if (d[j] >= k - 1) :

			# Add the vertex to store
			vertices[l] = j;

			# If the graph is not a clique of size k
			# then it cannot be a clique
			# by adding another edge
			if (is_clique(l + 1)) :

				# If the length of the clique is
				# still less than the desired size
				if (l < k) :

					# Recursion to add vertices
					find_clique(j, l + 1, k);

				# Size is met
				else :
					print_clique(l + 1);

SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' (388575726.py, line 5)

In [67]:
if __name__ == "__main__" :

	edges = [ [ 1, 2 ],
			[ 2, 3 ],
			[ 3, 1 ],
			[ 4, 3 ],
			[ 4, 5 ],
			[ 5, 3 ] ];
	k = 3;
	size = len(edges);
	n = 5;

	for i in range(size) :
		graph[edges[i][0]][edges[i][1]] = 1;
		graph[edges[i][1]][edges[i][0]] = 1;
		d[edges[i][0]] += 1;
		d[edges[i][1]] += 1;
	

	findCliques(0, 1, k);