In [92]:
%matplotlib inline
import matplotlib.pyplot as plt
from itertools import combinations
from random import random
import numpy as np

In [93]:
x = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[-1, -2, -3],
               [-4, -5, -6],
               [-7, -8, -9]],
               [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])
x.shape

(3, 3, 3)

In [94]:
y = x.ravel() # flatten out to a 1D array
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -1, -2, -3, -4, -5, -6, -7, -8,
       -9,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [95]:
print(x[1,2,0])
lin_index = np.where(y == x[1,2,0])
lin_index[0][0]

-7


15

In [96]:
def find_lin_ind(i, j, k, n):
    return (i * n ** 2 + j * n + k)

In [97]:
#
# Generate n-dimensional tensor
#
# # n = 3
# row = np.array([0 for i in range(0, n)])
# # row
# x = np.array([np.array([row for i in range(n)]) for i in range(n)])
# x


In [130]:
# g: tensor
# n: rank of the tensor
# p: probability of creating edges
node_val = {}
def generate_graph(n, p):
    # def add_to_dic(ind):
    #     if g[i, j, k] not in node_val.keys():
    #                     node_val.append((g[i, j, k[]: 1))
    #                 else:
    #                     node_val.[g[i, j, k]]= 1
    #                 print(vec)
    # Generate n-dimensional tensor
    # row = np.array([0 for i in range(0, n)])
    g = np.array([np.array([np.array([0 for i in range(0, n)]) for i in range(n)]) for i in range(n)])

    # generate 1-by-n^3 vector to track every node; 1 if included in a graph
    vec = g.ravel()
    print(vec)

    # Set edges
    for i in range(n):
        for j in range(n):
            for k in range(n):
                a = np.random.rand()
                # print(a)
                if a < p:
                    g[i, j, k] = 1
                    print(g)
                    vec[find_lin_ind(i, j, k, n)] += 1
                    if g[i, j, k] not in node_val.keys():
                        node_val[find_lin_ind(i, j, k, n)] += 1
                    else:
                        node_val[find_lin_ind(i, j, k, n)].append(1)
               
                    
                    g[i, k, j] = 1
                    vec[find_lin_ind(i, k, j, n)] += 1
                    if g[i, j, k] not in node_val.keys():
                        node_val[find_lin_ind(i, j, k, n)] += 1
                    else:
                        node_val[find_lin_ind(i, j, k, n)].append(1)
                        
                    g[j, i, k] = 1
                    vec[find_lin_ind(j, i, k,n)] += 1
                    g[j, k, i] = 1
                    vec[find_lin_ind(j, k, i, n)] += 1
                    g[k, i, j] = 1
                    vec[find_lin_ind(k, i, j, n)] += 1
                    g[k, j, i] = 1
                    vec[find_lin_ind(k, j, i, n)] += 1
    return g, vec, node_val


In [131]:
n = 3
p = 0.5
res = generate_graph(3, 0.5)
G = res[0]
node_val = res[2]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[[1 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


KeyError: 0

In [103]:
vec = res[1]
vec

array([0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2,
       2, 0, 0, 0, 2])

In [106]:
np.sort(vec)
reversed = np.sort(vec)[::-1]
reversed

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 0, 0])

In [107]:
begin = reversed[0]

In [ ]:
import random

# n: size
# order: k
def generate_random_hypergraph(order, n):
    nodes = set(range(order))
    edges = set()
    while len(edges) < size:
        edge_size = random.randint(2, order)
        edge = frozenset(random.sample(nodes, k=edge_size))
        if edge not in edges:
          edges.add(edge)
    return {'nodes': nodes, 'edges': edges}

In [ ]:
MAX = 20;

# list of the vertices - 1D array
vertices = [0]* MAX;
print(vertices)

# Graph - 
graph = np.zeros((MAX, MAX));
print(graph)

# Degree of the vertices
d = [0] * MAX;

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [ ]:
# Function to print the clique
def print_clique(n) :
	for i in range(1, n) :
		print(vertices[i], end = " ");
	print(",", end=" ");

In [ ]:
# recursively  find all the cliques of size s
def find_clique(i, l, k) :

	# Check if any vertices from i+1 can be inserted
	for j in range( i + 1, n -(k - l) + 1) :

		# If the degree of the graph is sufficient
		if (d[j] >= k - 1) :

			# Add the vertex to store
			vertices
			[l] = j;

			# If the graph is not a clique of size k
			# then it cannot be a clique
			# by adding another edge
			if (is_clique(l + 1)) :

				# If the length of the clique is
				# still less than the desired size
				if (l < k) :

					# Recursion to add vertices
					find_clique(j, l + 1, k);

				# Size is met
				else :
					print_clique(l + 1);

In [ ]:
edges = [ [ 1, 2 ],
			[ 2, 3 ],
			[ 3, 1 ],
			[ 4, 3 ],
			[ 4, 5 ],
			[ 5, 3 ] ];
k = 1;
size = len(edges);
n = 5;
for i in range(size) :
	graph[edges[i][0]][edges[i][1]] = 1;
	graph[edges[i][1]][edges[i][0]] = 1;
	d[edges[i][0]] += 1;
	d[edges[i][1]] += 1;
	

print(findCliques(0, 1, k)

0 , 0 , 0 , 0 , 0 , None
