In [216]:
%matplotlib inline
import matplotlib.pyplot as plt
from itertools import combinations
from random import random
import numpy as np

In [217]:
# def ER(n, p):
#     V = set([v for v in range(n)])
#     E = set()
#     for combination in combinations(V, 2):
#         a = random()
#         if a < p:
#             E.add(combination)

#     g = nx.Graph()
#     g.add_nodes_from(V)
#     g.add_edges_from(E)

#     return g
# p = 0.4
# G = ER(n, p)
# pos = nx.spring_layout(G)
# nx.draw_networkx(G, pos)
# plt.title("Random Graph Generation Example")
# plt.show()

In [218]:
x = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[-1, -2, -3],
               [-4, -5, -6],
               [-7, -8, -9]],
               [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])
x.shape

(3, 3, 3)

In [219]:
y = x.ravel() # flatten out to a 1D array
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -1, -2, -3, -4, -5, -6, -7, -8,
       -9,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [220]:
print(x[1,2,0])
lin_index = np.where(y == x[1,2,0])
lin_index[0][0]

-7


15

In [221]:
def find_lin_ind(i, j, k, n):
    return (i * n ** 2 + j * n + k)

In [222]:
#
# Generate n-dimensional tensor
#
# # n = 3
# row = np.array([0 for i in range(0, n)])
# # row
# x = np.array([np.array([row for i in range(n)]) for i in range(n)])
# x


In [223]:
# g: tensor
# n: rank of the tensor
# p: probability of creating edges
def generate_graph(n, p):
    # Generate n-dimensional tensor
    # row = np.array([0 for i in range(0, n)])
    g = np.array([np.array([np.array([0 for i in range(0, n)]) for i in range(n)]) for i in range(n)])

    # generate 1-by-n^3 vector to track every node; 1 if included in a graph
    vec = g.ravel()
    print(vec)

    # Set edges
    for i in range(n):
        for j in range(n):
            for k in range(n):
                a = np.random.rand()
                # print(a)
                if a < p:
                    g[i, j, k] = 1
                    print(g)
                    vec[find_lin_ind(i, j, k, n)] += 1
                    print(vec)
                    g[i, k, j] = 1
                    vec[find_lin_ind(i, k, j, n)] += 1
                    g[j, i, k] = 1
                    vec[find_lin_ind(j, i, k,n)] += 1
                    g[j, k, i] = 1
                    vec[find_lin_ind(j, k, i, n)] += 1
                    g[k, i, j] = 1
                    vec[find_lin_ind(k, i, j, n)] += 1
                    g[k, j, i] = 1
                    vec[find_lin_ind(k, j, i, n)] += 1
    return g, vec

In [224]:
n = 3
p = 0.5
res = generate_graph(3, 0.5)
G = res[0]
G

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[[0 0 0]
  [0 0 0]
  [0 1 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[[0 0 0]
  [0 0 2]
  [0 2 0]]

 [[1 0 2]
  [0 0 0]
  [2 0 0]]

 [[0 2 0]
  [2 0 0]
  [0 0 0]]]
[0 0 0 0 0 2 0 2 0 2 0 2 0 0 0 2 0 0 0 2 0 2 0 0 0 0 0]
[[[0 2 0]
  [2 0 2]
  [0 2 0]]

 [[2 1 2]
  [0 0 0]
  [2 0 0]]

 [[0 2 0]
  [2 0 0]
  [0 0 0]]]
[0 2 0 2 0 2 0 2 0 2 2 2 0 0 0 2 0 0 0 2 0 2 0 0 0 0 0]
[[[0 2 0]
  [2 2 2]
  [0 2 0]]

 [[2 2 2]
  [2 0 1]
  [2 0 0]]

 [[0 2 0]
  [2 0 0]
  [0 0 0]]]
[0 2 0 2 2 2 0 2 0 2 2 2 2 0 2 2 0 0 0 2 0 2 0 0 0 0 0]
[[[0 2 0]
  [2 2 2]
  [0 2 0]]

 [[2 2 2]
  [2 0 2]
  [1 2 0]]

 [[0 2 0]
  [2 2 0]
  [0 0 0]]]
[0 2 0 2 2 2 0 2 0 2 2 2 2 0 2 2 2 0 0 2 0 2 2 0 0 0 0]
[[[0 2 0]
  [2 2 2]
  [0 2 0]]

 [[2 2 2]
  [2 0 2]
  [2 1 0]]

 [[0 2 0]
  [2 2 0]
  [0 0 0]]]
[0 2 0 2 2 2 0 2 0 2 2 2 2 0 2 2 2 0 0 2 0 2 2 0 0 0 0]
[[[0 2 0]
  [2 2 2]
  [0 2 0]]



array([[[0, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 0, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 0]]])

In [225]:
vec = res[1]
vec


array([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0])